### ISSUE TITLE
Multiple inheritance chain error

### ISSUE THREAD

**Issue by ddabrahim** [Sheepolution/classroom#1]
Hi.

I am trying to implement multiple inheritance but when I use more than 2 in a chain, I get the following error:

classroom.lua 898: attempt to index field '_P' (a nil value)

This is how my code looks like

Car.lua
```
local Car = Class()
Car.wheels = 0
function Car:constructor(_wheels)
  self.wheels = _wheels
end

return Car
```

FamilyCar.lua
```
local Car = require "Car"

local FamilyCar = Car:extend()
FamilyCar.seats = 0
function FamilyCar:constructor(_seats, _wheels)
  FamilyCar.super(self, _wheels)
  self.seats = _seats
end

return FamilyCar

```

SportCar.lua
```
local FamilyCar = require "FamilyCar"

 local SportCar = FamilyCar:extend()
 SportCar.engine = ""
 function SportCar:constructor(_engine, _seats, _wheels)
   SportCar.super(self, _seats, _wheels)
   SportCar.engine = _engine
 end

 return SportCar
```

main.lua
```
Class = require "classroom"

local FamilyCar = require "FamilyCar"
local SportCar = require "SportCar"

peugeot = FamilyCar(4,4)
ferrari = SportCar("V8", 2, 4) --this is causing the error

function love.draw()
  love.graphics.print(peugeot.wheels)
end
```

Here is a project that reproduce the problem:
[classroomtest.zip](https://github.com/Sheepolution/classroom/files/8597855/classroomtest.zip)

I am uncertain if is it a bug, limitation or something I am doing wrong.
I would appreciate any help.

Using:
LOVE 11.4
classroom.lua
macOS 12.3.1

Thank you.

**Comment by Sheepolution** [comment]
Sorry about this. I'm gonna look into it.

**Comment by ddabrahim** [comment]
Thanks a lot. Appreciate it!

I do actually have similar problem with all OOP library except others cause love2d to crash with the error

Error: [love "boot.lua"]:48: Failed to initialize filesystem: already initialized

Received no reply from others yet.
Glad you've been able to find a work-around.

Thanks.
